"""empty message

Revision ID: 225a6f2761f1
Revises: f2d2b34f0834
Create Date: 2022-10-31 13:42:53.343583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225a6f2761f1'
down_revision = 'f2d2b34f0834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'state')
    # ### end Alembic commands ###
