"""empty message

Revision ID: 51b032054227
Revises: 7b341695f43f
Create Date: 2022-10-27 13:44:38.194979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b032054227'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('stock', sa.String(length=80), nullable=False),
    sa.Column('sale_price', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=80), nullable=False),
    sa.Column('purchase_price', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_name', sa.String(length=80), nullable=False),
    sa.Column('type_of_muscle', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('activities', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('birthday', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('ci', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('date_of_admission', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('medical_conditions', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('medicines', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('mutualist', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=9), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('training_goals', sa.String(length=80), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['ci'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'training_goals')
    op.drop_column('user', 'role')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'mutualist')
    op.drop_column('user', 'medicines')
    op.drop_column('user', 'medical_conditions')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'date_of_admission')
    op.drop_column('user', 'ci')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'activities')
    op.drop_table('training')
    op.drop_table('product')
    # ### end Alembic commands ###
