"""empty message

Revision ID: 62ad2c34cd24
Revises: 20fced19c8fd
Create Date: 2022-11-11 20:34:31.789149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ad2c34cd24'
down_revision = '20fced19c8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('idCarrito', sa.Integer(), nullable=False))
    op.add_column('shopping_cart', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.add_column('shopping_cart', sa.Column('precio', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'precio')
    op.drop_column('shopping_cart', 'cantidad')
    op.drop_column('shopping_cart', 'idCarrito')
    # ### end Alembic commands ###
