"""empty message

Revision ID: 6ead12ba9c9b
Revises: 8f92b7802d3b
Create Date: 2022-10-31 19:24:16.845957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ead12ba9c9b'
down_revision = '8f92b7802d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('description', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'description')
    # ### end Alembic commands ###
