"""empty message

Revision ID: fecf621061e5
Revises: 2577d0a0df2c
Create Date: 2022-11-04 20:09:39.082822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecf621061e5'
down_revision = '2577d0a0df2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutinaejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idRutina', sa.Integer(), nullable=True),
    sa.Column('idEjercicios', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Integer(), nullable=True),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('finaliza', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['idEjercicios'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['idRutina'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('routines', 'repetitions')
    op.drop_column('routines', 'burden')
    op.drop_column('routines', 'finish')
    op.drop_column('routines', 'week')
    op.drop_column('routines', 'series')
    op.add_column('user', sa.Column('cuota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cuota')
    op.add_column('routines', sa.Column('series', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('routines', sa.Column('week', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('routines', sa.Column('finish', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('routines', sa.Column('burden', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('routines', sa.Column('repetitions', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_table('rutinaejercicios')
    # ### end Alembic commands ###
